# Generated by Django 5.1.6 on 2025-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swaporder',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('platform', 'Platform Shipping'), ('self', 'Self Exchange')], max_length=20, null=True),
        ),
    ]
