# Generated by Django 5.1.6 on 2025-03-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0004_address_house_no_or_name_address_landmark'),
        ('esc_trader', '0005_trader_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='esc_trader.trader'),
        ),
    ]
