# Generated by Django 5.1.6 on 2025-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0005_alter_address_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('swap', 'Swap Shipping Service'), ('self', 'Self Exchange')], default='swap', max_length=20, null=True),
        ),
    ]
