# Generated by Django 5.1.6 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0009_shippingdetails_current_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
