# Generated by Django 5.1.6 on 2025-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0012_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaporder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
