# Generated by Django 5.1.6 on 2025-04-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0014_swaporder_escrow_transaction'),
        ('esc_transaction', '0013_alter_tokentransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaporder',
            name='ownership_transfer_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='esc_transaction.nfttransaction'),
        ),
        migrations.AlterField(
            model_name='swaporder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('escrow', 'Escrow'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
