# Generated by Django 5.1.6 on 2025-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0015_swaporder_ownership_transfer_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaporder',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
