# Generated by Django 5.1.6 on 2025-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_order', '0016_alter_swaporder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaporder',
            name='ownership_transfer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaporder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('escrow', 'Escrow'), ('paid', 'Paid'), ('processing', 'Processing'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
