# Generated by Django 5.1.6 on 2025-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_hub', '0003_alter_route_cost_alter_route_distance_and_more'),
        ('esc_order', '0017_swaporder_ownership_transfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='shipping_route',
            field=models.ManyToManyField(to='esc_hub.route'),
        ),
    ]
