# Generated by Django 5.1.6 on 2025-02-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esc_nft', '0001_initial'),
        ('esc_product', '0001_initial'),
        ('esc_trader', '0005_trader_wallet'),
        ('esc_transaction', '0002_nftminttransaction_nfttransfertransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='creation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft_creation', to='esc_transaction.nftminttransaction', verbose_name='NFT Mint Transactino'),
        ),
        migrations.AddField(
            model_name='nft',
            name='lifecycle',
            field=models.ManyToManyField(blank=True, related_name='nft_lifecycle', to='esc_transaction.nfttransfertransaction', verbose_name='NFT Transfer History'),
        ),
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to='esc_trader.trader'),
        ),
        migrations.AddField(
            model_name='nft',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associated_nfts', to='esc_product.product'),
        ),
    ]
