# Generated by Django 5.1.6 on 2025-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='lifecycle',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='token_id',
        ),
        migrations.AddField(
            model_name='nft',
            name='exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nft',
            name='leaf_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='tree_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
