# Generated by Django 5.1.6 on 2025-02-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0003_remove_nft_lifecycle_remove_nft_token_id_and_more'),
        ('esc_transaction', '0006_remove_tokentransaction_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='creation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft_creation', to='esc_transaction.nftminttransaction', verbose_name='NFT Mint Transaction'),
        ),
    ]
