# Generated by Django 5.1.6 on 2025-02-25 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0004_alter_nft_creation'),
        ('esc_product', '0003_rename_main_product_maincategory_and_more'),
        ('esc_trader', '0005_trader_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to='esc_trader.trader'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_nfts', to='esc_product.product'),
        ),
    ]
