# Generated by Django 5.1.6 on 2025-02-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0006_alter_nft_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='image',
            new_name='mainImage',
        ),
    ]
