# Generated by Django 5.1.6 on 2025-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0007_rename_image_nft_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='mainImage',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nft_images/'),
        ),
    ]
