# Generated by Django 5.1.6 on 2025-03-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0008_alter_nft_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='creation',
        ),
    ]
