# Generated by Django 5.1.6 on 2025-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0009_remove_nft_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='nft_type',
            field=models.CharField(choices=[('NFT', 'nft'), ('CNFT', 'cnft')], max_length=50, null=True),
        ),
    ]
