# Generated by Django 5.1.6 on 2025-03-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0010_nft_nft_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='nft_type',
            new_name='nftType',
        ),
    ]
