# Generated by Django 5.1.6 on 2025-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0011_rename_nft_type_nft_nfttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='in_processing',
            field=models.BooleanField(default=False),
        ),
    ]
