# Generated by Django 5.1.6 on 2025-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0012_nft_in_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
