# Generated by Django 5.1.6 on 2025-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0013_nft_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='total_owners',
            field=models.IntegerField(default=1),
        ),
    ]
