# Generated by Django 5.1.5 on 2025-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_user', '0002_alter_ecouser_options_alter_ecouser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecouser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
