# Generated by Django 5.1.5 on 2025-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_user', '0003_ecouser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ecouser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ecouser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ecouser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ecouser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='ecouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ecouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
