# Generated by Django 5.1.5 on 2025-02-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0002_alter_trader_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='last_name',
        ),
    ]
