# Generated by Django 5.1.6 on 2025-02-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0003_remove_trader_first_name_remove_trader_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='wallet_address',
        ),
    ]
