# Generated by Django 5.1.6 on 2025-02-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0004_remove_trader_wallet_address'),
        ('esc_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='esc_wallet.wallet', verbose_name='Main Wallet'),
        ),
    ]
