# Generated by Django 5.1.6 on 2025-04-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0005_trader_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='owned_assets',
            field=models.IntegerField(default=0),
        ),
    ]
