# Generated by Django 5.1.6 on 2025-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esc_transaction', '0002_nftminttransaction_nfttransfertransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('private_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('balance', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('transactions', models.ManyToManyField(related_name='wallet_transactions', to='esc_transaction.tokentransaction')),
            ],
        ),
    ]
