# Generated by Django 5.1.6 on 2025-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='key',
            field=models.CharField(db_index=True, default=int, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(db_index=True, max_length=600, unique=True),
        ),
    ]
