# Generated by Django 5.1.6 on 2025-02-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_wallet', '0002_wallet_key_alter_wallet_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transactions',
        ),
    ]
