# Generated by Django 5.1.6 on 2025-04-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_wallet', '0004_escrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Escrow',
        ),
    ]
