# Generated by Django 5.1.6 on 2025-03-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_product', '0003_rename_main_product_maincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='additionalMaterials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.FloatField(blank=True, help_text='Estimated carbon footprint in kg CO2e.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cruelity_free',
            field=models.BooleanField(default=False, help_text='Is the product cruelty-free?'),
        ),
        migrations.AddField(
            model_name='product',
            name='destructable',
            field=models.BooleanField(default=False, help_text='Is the product destructible?'),
        ),
        migrations.AddField(
            model_name='product',
            name='durability',
            field=models.IntegerField(blank=True, help_text='Expected lifespan in years.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_efficiency',
            field=models.FloatField(blank=True, help_text='Energy consumption rating (e.g., kWh per year).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ethical_sourcing',
            field=models.BooleanField(default=False, help_text='Are materials ethically sourced?'),
        ),
        migrations.AddField(
            model_name='product',
            name='hazardous',
            field=models.BooleanField(default=False, help_text='Is the product hazardous?'),
        ),
        migrations.AddField(
            model_name='product',
            name='natural',
            field=models.BooleanField(default=False, help_text='Is the product made from natural materials?'),
        ),
        migrations.AddField(
            model_name='product',
            name='plastic_free',
            field=models.BooleanField(default=False, help_text='Is the product plastic-free?'),
        ),
        migrations.AddField(
            model_name='product',
            name='recyclability',
            field=models.BooleanField(default=False, help_text='Is the product recyclable?'),
        ),
        migrations.AddField(
            model_name='product',
            name='recycled_content',
            field=models.FloatField(blank=True, help_text='Percentage of recycled materials used (0-100).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='repairability_score',
            field=models.FloatField(blank=True, help_text='Ease of repairability score (0-10).', null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('certificationNumber', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='esc_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper'), ('fabric', 'Fabric'), ('ceramic', 'Ceramic'), ('rubber', 'Rubber'), ('leather', 'Leather'), ('stone', 'Stone'), ('bamboo', 'Bamboo'), ('cotton', 'Cotton'), ('silk', 'Silk'), ('wool', 'Wool'), ('linen', 'Linen'), ('hemp', 'Hemp'), ('jute', 'Jute'), ('coir', 'Coir'), ('sisal', 'Sisal'), ('cork', 'Cork')], max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='esc_product.product')),
            ],
        ),
    ]
