# Generated by Django 5.1.6 on 2025-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_product', '0004_remove_product_material_product_additionalmaterials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='additionalMaterials',
            new_name='additional_materials',
        ),
    ]
