# Generated by Django 5.1.6 on 2025-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_product', '0006_remove_materials_product_product_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_materials',
        ),
        migrations.AlterField(
            model_name='product',
            name='repairability_score',
            field=models.FloatField(blank=True, help_text='Ease of repairability score (0-100).', null=True),
        ),
    ]
