# Generated by Django 5.1.6 on 2025-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_product', '0008_product_owned_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('for_parts', 'For Parts or Not Working')], max_length=20, null=True),
        ),
    ]
