# Generated by Django 5.1.6 on 2025-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_product', '0009_alter_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sustainability_score',
            field=models.FloatField(blank=True, help_text='Sustainability score (0-100).', null=True),
        ),
    ]
