# Generated by Django 5.1.6 on 2025-02-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0004_remove_trader_wallet_address'),
        ('esc_transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTMintTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nft_name', models.CharField(max_length=100)),
                ('nft_symbol', models.CharField(default='NFT', max_length=10)),
                ('metadata_uri', models.URLField(blank=True, null=True)),
                ('mint_cost', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('mint_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('minted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minted_nfts', to='esc_trader.trader', verbose_name='Minted To')),
            ],
        ),
        migrations.CreateModel(
            name='NFTTransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nft_name', models.CharField(max_length=100)),
                ('nft_id', models.CharField(db_index=True, max_length=200)),
                ('previous_owner_duration', models.IntegerField(blank=True, null=True)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('transfered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nfts', to='esc_trader.trader', verbose_name='Sender')),
                ('transfered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nfts', to='esc_trader.trader', verbose_name='Receiver')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('REWARD', 'Reward')], max_length=20)),
                ('network_fees', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('transfered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_token_transactions', to='esc_trader.trader', verbose_name='Sender')),
                ('transfered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_token_transactions', to='esc_trader.trader', verbose_name='Receiver')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
