# Generated by Django 5.1.6 on 2025-02-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0003_remove_nft_lifecycle_remove_nft_token_id_and_more'),
        ('esc_transaction', '0002_nftminttransaction_nfttransfertransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftminttransaction',
            name='lifecycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mint_lifecycle', to='esc_nft.nft', verbose_name='NFT'),
        ),
    ]
