# Generated by Django 5.1.6 on 2025-02-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_trader', '0005_trader_wallet'),
        ('esc_transaction', '0003_nftminttransaction_lifecycle'),
        ('esc_wallet', '0003_remove_wallet_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransaction',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='tokentransaction',
            name='network_fees',
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='transactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='esc_wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transfered_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_token_transactions', to='esc_trader.trader', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transfered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_token_transactions', to='esc_trader.trader', verbose_name='Receiver'),
        ),
    ]
