# Generated by Django 5.1.6 on 2025-02-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0004_remove_tokentransaction_block_number_and_more'),
        ('esc_wallet', '0003_remove_wallet_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='nftminttransaction',
            name='minted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minted_nfts', to='esc_wallet.wallet', verbose_name='Minted To'),
        ),
        migrations.AlterField(
            model_name='nfttransfertransaction',
            name='transfered_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nfts', to='esc_wallet.wallet', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='nfttransfertransaction',
            name='transfered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nfts', to='esc_wallet.wallet', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transfered_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_token_transactions', to='esc_wallet.wallet', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transfered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_token_transactions', to='esc_wallet.wallet', verbose_name='Receiver'),
        ),
    ]
