# Generated by Django 5.1.6 on 2025-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0005_remove_tokentransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransaction',
            name='transactions',
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('REWARD', 'Reward')], default='REWARD', max_length=20),
        ),
    ]
