# Generated by Django 5.1.6 on 2025-03-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0009_remove_nft_creation'),
        ('esc_transaction', '0006_remove_tokentransaction_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftminttransaction',
            name='lifecycle',
        ),
        migrations.RemoveField(
            model_name='nftminttransaction',
            name='metadata_uri',
        ),
        migrations.RemoveField(
            model_name='nftminttransaction',
            name='nft_name',
        ),
        migrations.RemoveField(
            model_name='nftminttransaction',
            name='nft_symbol',
        ),
        migrations.AddField(
            model_name='nftminttransaction',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mint_lifecycle', to='esc_nft.nft', verbose_name='NFT'),
        ),
        migrations.AddField(
            model_name='nftminttransaction',
            name='transaction_type',
            field=models.CharField(default='MINT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('REWARD', 'Reward'), ('FEE', 'Fee')], default='REWARD', max_length=20),
        ),
    ]
