# Generated by Django 5.1.6 on 2025-03-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0007_remove_nftminttransaction_lifecycle_and_more'),
        ('esc_wallet', '0003_remove_wallet_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFTTransferTransaction',
            new_name='NFTTransaction',
        ),
    ]
