# Generated by Django 5.1.6 on 2025-03-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_nft', '0011_rename_nft_type_nft_nfttype'),
        ('esc_transaction', '0008_rename_nfttransfertransaction_nfttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfttransaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='esc_nft.nft', verbose_name='NFT'),
        ),
    ]
