# Generated by Django 5.1.6 on 2025-03-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0009_nfttransaction_asset'),
        ('esc_wallet', '0003_remove_wallet_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfttransaction',
            name='nft_id',
        ),
        migrations.RemoveField(
            model_name='nfttransaction',
            name='nft_name',
        ),
        migrations.RemoveField(
            model_name='nfttransaction',
            name='previous_owner_duration',
        ),
        migrations.RemoveField(
            model_name='nfttransaction',
            name='transfer_reason',
        ),
        migrations.AddField(
            model_name='nfttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='nfttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('mint', 'MINT'), ('transfer', 'Transfer')], default='MINT', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfttransaction',
            name='transfered_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_nfts', to='esc_wallet.wallet', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='nfttransaction',
            name='transfered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_nfts', to='esc_wallet.wallet', verbose_name='Receiver'),
        ),
    ]
