# Generated by Django 5.1.6 on 2025-04-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0011_escrowtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='purpose',
            field=models.CharField(choices=[('PURCHASE', 'Purchase')], default='PURCHASE', max_length=20),
        ),
    ]
