# Generated by Django 5.1.6 on 2025-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_transaction', '0012_escrowtransaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HOLD', 'Hold'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('ESCROW', 'Escrow'), ('REWARD', 'Reward'), ('FEE', 'Fee')], default='REWARD', max_length=20),
        ),
        migrations.DeleteModel(
            name='EscrowTransaction',
        ),
    ]
